name: test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.9.1
        with:
          version: v1.8.3

      - name: Show Forge version
        run: forge --version

      - name: Lint
        run: forge lint -D warnings

      - name: Build
        run: forge build --sizes

      - name: Test
        run: forge test -vvv
